name: Terraform

on:
  push:
    branches:
      - feature_branch_1

  pull_request:
    branches:
      - feature_branch_1

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::237162087889:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: terraform-practice
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform-practice
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform-practice
        run: terraform plan -out=tfplan